name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.check.outputs.should_publish }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if version changed
        id: check
        run: |
          # Read version with error handling
          CURRENT_VERSION=$(node -p "require('./package.json').version" 2>/dev/null)
          if [ -z "$CURRENT_VERSION" ]; then
            echo "Error: Failed to read package.json version"
            exit 1
          fi
          echo "Current version: $CURRENT_VERSION"
          
          # Check if this version tag already exists
          if git ls-remote --tags origin | grep -q "refs/tags/v${CURRENT_VERSION}$"; then
            echo "Version v${CURRENT_VERSION} already published"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected: v${CURRENT_VERSION}"
            echo "should_publish=true" >> $GITHUB_OUTPUT
            echo "version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: check-version
    if: needs.check-version.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # LTS version
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Run comprehensive tests
        run: |
          # Test that the CLI works
          npm link
          ccstats --version
          ccstats --help
          
          # Test with sample JSONL file
          echo '{"type":"session_start","timestamp":"2024-01-01T00:00:00.000Z","sessionId":"test-123"}' > test.jsonl
          echo '{"type":"user","timestamp":"2024-01-01T00:00:01.000Z"}' >> test.jsonl
          echo '{"type":"assistant","timestamp":"2024-01-01T00:00:02.000Z"}' >> test.jsonl
          
          # Test different output formats
          ccstats -f test.jsonl -o json > /dev/null
          ccstats -f test.jsonl -o yaml > /dev/null
          
          # Cleanup
          rm test.jsonl
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          name: Release v${{ needs.check-version.outputs.version }}
          body: |
            ## 🚀 Released version ${{ needs.check-version.outputs.version }}
            
            This release was automatically published to npm.
            
            ### Installation
            ```bash
            npm install -g ccstats@${{ needs.check-version.outputs.version }}
            ```
            
            ### Usage
            ```bash
            npx ccstats@${{ needs.check-version.outputs.version }}
            ```
            
            See [npm package](https://www.npmjs.com/package/ccstats/v/${{ needs.check-version.outputs.version }}) for more details.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}